services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"

  user-service:
    build: ./user-service
    ports:
      - "4000:4000"
    env_file:
      - .env

  event-service:
    build: ./event-service
    ports:
      - "5000:5000"
    env_file:
      - .env

  booking-service:
    build: ./booking-service
    ports:
      - "6000:6000"
    depends_on:
      - mongo
      - rabbitmq
      - event-service
    env_file:
      - .env

  notification-service:
    build: ./notification-service

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  
  admin-panel:
    build: ./admin-panel
    ports:
      - "5173:5173"